name: copy_with_extension
version: 2.0.0-nullsafety.1
description: Annotation for generating `copyWith` extensions code using `copy_with_extension_gen`.
homepage: https://github.com/numen31337/copy_with_extension/tree/master/copy_with_extension
repository: https://github.com/numen31337/copy_with_extension
issue_tracker: https://github.com/numen31337/copy_with_extension/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: 
  build_runner: ^1.11.1
  test: 