name: copy_with_extension_gen
version: 2.0.0-nullsafety.1
description: Automatically generating `copyWith` extensions code for classes with `@CopyWith()` annotation.
repository: https://github.com/numen31337/copy_with_extension
homepage: https://github.com/numen31337/copy_with_extension/tree/master/copy_with_extension_gen
issue_tracker: https://github.com/numen31337/copy_with_extension/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.41.2
  build: ^1.0.0
  source_gen: ^0.9.10+1
  copy_with_extension: 
    git:
      url: git@github.com:josiahsrc/copy_with_extension.git
      path: copy_with_extension

dev_dependencies:
  pedantic: 
  build_runner: ^1.11.1
  logging: ^0.11.4
  build_test: ^1.3.6
  test: 